// src/frontend/src/app/testcentre/components/Question.tsx
type QuestionProps = {
    recordAnswer: (questionId: string, answer: string) => void;
    questionText: string;
    answers: Map<string, string>;
    questionId: string;
    questionNumber: number;
    disabled: boolean;
}

export default function Question({ recordAnswer, questionText, answers, questionId, questionNumber, disabled }: QuestionProps) {

    return (<div>
        <div className="field box question">
            <label className="label">
                <strong> Question {questionNumber + 1}:</strong>
                <em> {questionText}</em>
            </label>
            <div className="control">
                <div className="select is-fullwidth">
                    <select
                        required
                        disabled={disabled}
                        onChange={(e) => { recordAnswer(questionId, e.target.value) }}
                    >
                        <option disabled selected value="">Please select one</option>
                        {Object.entries(answers).map(([optionId, optionText],) => (
                            <option
                                value={optionId}
                                key={optionId}
                            >
                                {optionText}
                            </option>))}
                    </select>
                </div>
            </div>
            <p className="help">Choose the best option.</p>
        </div>

    </div>);
}

// src/frontend-vue/testcentre/src/components/Question.vue
<template>
  <div class="field box question">
    <label className="label">
      <strong> Question {{questionNumber + 1}}:</strong>
      <em> {{questionText}}</em>
      </label>
    <div class="control">
      <div class="select is-fullwidth">
        <select
          required
          :disabled="exam_disabled == 1"
          @change="questionAnswered"
          v-model="selected"
        >
          <option disabled selected value="">Please select one</option>
          <option
            v-for="(text, value) in answers"
            v-bind:value="value"
            v-bind:key="value"
          >
           {{text}}
          </option>
        </select>
      </div>
    </div>
    <p class="help">Choose the best option.</p>
  </div>
</template>

<script>
import ExamEventBus from './ExamEventBus';

export default {
  name: 'Question',
   data() {
    return {
      selected: '',
      exam_disabled: false
    }
  },
  props: {
    // Unique identifier for question.
    questionId: String,
    // Question sequence number (index in array of questions).
    questionNumber: Number,
    // Text of questions.
    questionText: String,
    // An Object map of answers for the question.
    answers: Object,
  },
  mounted() {
    // Disable the form if this exam has been sent back to StepFunctions.
    ExamEventBus.$on('examPostedSuccessfully', () => {
      this.exam_disabled = true;
    });
  },
  methods: {
    questionAnswered() {
      this.$emit('record-answer', this.questionId, this.selected);
    }
  }
}
</script>
